"use client";

import Lottie from "lottie-react";
// import { Metadata } from "next";
import Link from "next/link";
import failedLottie from "@/public/assets/lotties/fail.json";

// export const metadata: Metadata = {
//   title: "پرداخت ناموفق",
//   description: "Generated by create next app",
// };

const Failed = () => {
  return (
    <div className="flex_center flex-col h-[60vh]">
      <Lottie animationData={failedLottie} loop={true} className="w-44 h-44" />
      <h1 className="text-2xl font-bold text-[#ec2e5e]">پرداخت ناموفق</h1>
      <p className="mt-2 text-base text-black">مشکلی در پرداخت پیش آمده است.</p>
      <Link
        href="/dashboard?tab=order"
        className="mt-6 px-4 py-2 bg-[#ec2e5e] text-white rounded-lg"
      >
        بازگشت به صفحه اصلی
      </Link>
    </div>
  );
};

export default Failed;
