"use client";

import Lottie from "lottie-react";
// import { Metadata } from "next";
import Link from "next/link";
import successLottie from "@/public/assets/lotties/success.json";

// export const metadata: Metadata = {
//   title: "پرداخت موفق",
//   description: "Generated by create next app",
// };

const Success = () => {
  return (
    <div className="flex_center flex-col h-[60vh]">
      <Lottie animationData={successLottie} loop={true} className="w-28 h-28" />

      <h1 className="text-2xl font-bold text-green-600">پرداخت موفق</h1>
      <p className="mt-2 text-black text-base">
        سفارشتان را می توانید از طریق کد سفارش، رهگیری کنید.
      </p>
      <Link
        href="/dashboard?tab=order"
        className="mt-6 px-4 py-2 bg-green-500 text-white rounded-lg"
      >
        بازگشت به صفحه اصلی
      </Link>
    </div>
  );
};

export default Success;
