import { Metadata } from "next";
import Carousel from "@/components/shared/Carousel";
import axiosInstance from "@/lib/axiosInstance";
import ProductDetails from "@/components/shared/ProductDetails";

async function fetchProduct(id: string) {
  try {
    const { data } = await axiosInstance.get(`products/${id}`);
    return data;
  } catch (error) {
    console.log(error);
  }
}

export async function generateMetadata({
  params,
}: {
  params: { id: string };
}): Promise<Metadata> {
  const { data } = await fetchProduct(params.id);

  return {
    title: data ? data.name : "محصولات",
    description: data
      ? data.description || "خرید بهترین محصولات با کیفیت بالا"
      : "Generated by create next app",
  };
}

const Page = async ({ params }: { params: { id: string } }) => {
  const { data: product } = await fetchProduct(params.id);

  return (
    <>
      <ProductDetails product={product} />

      <section className="w-full mt-8 container mx-auto px-10">
        <div className="bg-yellow_300 p-4 rounded-xl">
          <h2 className="text-xl text-black font-medium mb-4">مشخصات</h2>

          <div className="flex gap-10">
            <span className="">جنس</span>
            <div className="flex-column">
              <span className="">الیاف نخی</span>
              <span className="">پلی استر</span>
            </div>
          </div>
        </div>
      </section>

      <Carousel
        title="محصولات جدید"
        side="right"
        seeAllLink="products/best-selling"
        carouselBg="white"
        api="/"
      />
    </>
  );
};

export default Page;
