import { Metadata } from "next";
import prisma from '@/lib/db';
import Carousel from "@/components/shared/Carousel";
// import { IProduct } from "@/types/model";
import ProductDetails from "@/components/shared/ProductDetails";

async function fetchProduct(id: string) {
  try {
    const product = await prisma.product.findUnique({
      where: { id: Number(id) },
      include: {
        brand: true,
        category: true,
        country: true,
        images: true,
        attributes: true,
        colorVariants: { include: { color: true } },
      },
    });

    return product;
  } catch (error) {
    console.error("❌ Error fetching product:", error);
    return null;
  }
}

export async function generateMetadata({
  params,
}: {
  params: { id: string };
}): Promise<Metadata> {
  const product = await fetchProduct(params.id);

  return {
    title: product ? product.name : "محصولات",
    description: product
      ? product.description || "خرید بهترین محصولات با کیفیت بالا"
      : "Generated by create next app",
  };
}

const Page = async ({ params }: { params: { id: string } }) => {
  const product = await fetchProduct(params.id);

  if (!product) {
    return (
      <section className="container mx-auto px-10 mt-8">
        <p className="text-red-600">محصول یافت نشد.</p>
      </section>
    );
  }

  return (
    <>
      <ProductDetails product={product} />

      <section className="w-full mt-8 container mx-auto px-10">
        <div className="p-4">
          <h2 className="text-xl text-black font-medium mb-4 pb-1 w-fit border-b-2 border-secondary-700">مشخصات</h2>

          {product.attributes.map(attr => (
            <div key={attr.id} className="flex gap-10 mb-4 border-b border-[#f0f0f1] py-4">
              <h4 className="w-1/3">{attr.key}</h4>
              <span className="w-2/3">{attr.value}</span>
            </div>
          ))}
        </div>
      </section>

      {product.category?.id && (
        <Carousel
          title="محصولات مرتبط"
          side="right"
          seeAllLink={`/products?limit=16&sortBy=createdAt&sortOrder=desc&categoryId=${product.category.id}`}
          carouselBg="secondary-500"
          innerCarouselBg='bg-white'
          linkClass="!text-white"
          titleClass="!text-white"
          api={`/products?categoryId=${product.category.id}&limit=16&sortBy=createdAt&sortOrder=desc`}
        />
      )}
    </>
  );
};

export default Page;
