import type { Metadata } from "next";
import ProgressBarProvider from "@/components/shared/ProgressBarProvider";
import AuthProvider from "@/components/shared/AuthProvider";
import { ReduxProvider } from "@/lib/store/ReduxProvider";
import { enBrandName } from "@/constants";
import "./globals.css";


export const metadata: Metadata = {
  title: {
    template: "%s | arshianbaft - فروشگاه آنلاین فروش پارچه",
    default: enBrandName,
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa-IR" dir="rtl">
      <body>
        <ReduxProvider>
          <AuthProvider>
            <ProgressBarProvider>
              {children}
            </ProgressBarProvider>
          </AuthProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
