import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";
import ProgressBarProvider from "@/components/shared/ProgressBarProvider";
import "./globals.css";
import AuthProvider from "@/components/shared/AuthProvider";
import { ReduxProvider } from "@/lib/store/ReduxProvider";


export const metadata: Metadata = {
  title: {
    template: "%s | Marin - فروشگاه آنلاین لباس زنانه",
    default: "Marin",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa-IR" dir="rtl">
      <body>
        <ReduxProvider>
          <AuthProvider>
            <ProgressBarProvider>
              {children}
              <ToastContainer />
            </ProgressBarProvider>
          </AuthProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
