'use client';

// import { Metadata } from "next";
import CustomPagination from "@/components/shared/CustomPagination";
import ProductCard from "@/components/shared/ProductCard";
import Filter from "@/components/shared/Filter";
import ProductsFilters from "@/components/shared/ProductsFilters";
import { IProduct } from "@/types";
import NoProduct from "@/components/shared/NoProduct";
import { useEffect, useState } from "react";

// export const metadata: Metadata = {
//   title: "محصولات",
//   description: "Generated by create next app",
// };

// async function fetchProducts(searchParams: Record<string, string | undefined>) {
//   try {
//     const filteredParams: Record<string, string> = Object.fromEntries(
//       Object.entries(searchParams)
//         .filter(([, value]) => value !== undefined)
//         .map(([key, value]) => [key, value as string])
//     );

//     const query = new URLSearchParams(filteredParams).toString();
//     const res = await fetch(`/api/products`);
//     const data = await res.json();
//     return data;
//   } catch (error) {
//     console.log("Error fetching products:", error);
//     return { data: [], pagination: {} };
//   }
// }

// const page = async ({searchParams}: {
//   searchParams: Record<string, string | undefined>;
// }) => {
const Page = () => {
  const [products, setProducts] = useState([]);
  const [pagination, setPagination] = useState({});
  // const response = await fetchProducts(searchParams);

  useEffect(() => {
    const fetchProducts = async () => {
      try {
        const res = await fetch('/api/products');
        const data = await res.json();

        setProducts(data.data);
        setPagination(data.pagination);
      } catch (error) {
        console.log(error)
      }
    };

    fetchProducts();
  }, [])

  // const loadedProducts = response?.data || [];
  // const pagination = response?.pagination || {};
  // const showFilters = searchParams.showFilters === "true";
  // console.log(loadedProducts);

  return (
    <section className="md:px-4 px-14 mt-10 min-h-[85vh] flex-column items-center justify-between">
      <div className="w-full flex items-start justify-center gap-4 flex-nowrap">
        {true && (
          <div className="w-1/4">
            <Filter />
          </div>
        )}

        <div className={`flex items-center justify-end gap-4 flex-wrap ${true ? "w-3/4" : "w-full"}`}>
          <ProductsFilters />

          {products.length ? (
            products?.map((item: IProduct) => (
              <div
                className={`w-[calc(50%-16px)] ${true
                  ? "md:w-[calc(33%-16px)]"
                  : "min-[900px]:w-[calc(33%-16px)] xl:w-[calc(25%-16px)]"
                  }`}
                key={item._id}
              >
                {/* <ProductCard
                  imgSrc={item.image[0]}
                  imgAlt={item.name}
                  imgWidth={1500}
                  imgHeight={900}
                  title={item.name}
                  stock={item.stock}
                  price={item.basePrice}
                  link={item._id}
                /> */}
              </div>
            ))
          ) : <NoProduct />}
        </div>
      </div>

      <CustomPagination pagination={pagination} />
    </section>
  );
};

export default Page;
