import Payment from "@/components/payment/Payment";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "نتیجه سفارش",
  description: "Generated by create next app",
};

const Page = () => {
  return <Payment />;
};

export default Page;
